[nrf fromlist] library: psa_crypto: Fix compilation error in psa_key_derivation_abort
Fix compilation error in psa_key_derivation_abort when
MBEDTLS_PSA_BUILTIN_ALG_TLS12_PRF is defined, but
MBEDTLS_PSA_BUILTIN_ALG_TLS12_PSK_TO_MS is not defined.

In function 'psa_key_derivation_abort':
error: 'psa_tls12_prf_key_derivation_t'
{aka 'struct psa_tls12_prf_key_derivation_s'} has no member named
'other_secret'

Upstream PR:
https://github.com/Mbed-TLS/mbedtls/pull/7125

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>